
if [[ -f ~/.bashrc ]]; then source ~/.bashrc; fi

export RUBY_HEAP_FREE_MIN=1024
export RUBY_GC_HEAP_INIT_SLOTS=4000000
export RUBY_HEAP_SLOTS_INCREMENT=250000
export RUBY_GC_MALLOC_LIMIT=500000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBYOPT=-Itest # so we can just invoke ruby test/unit/foo.rb. See https://github.com/svenfuchs/i18n/pull/68
export DYLD_LIBRARY_PATH="/usr/local/oracle/instantclient_11_2"
